formula     = white_space, expr, white_space, eof ;
expr        = { term, expr_op }, term ;
term        = { factor, term_op }, factor ;
factor      = const_val | paren_expr ;
const_val   = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' ;
paren_expr  = '(', white_space expr white_space, ')' ;
expr_op     = white_space, '+' | '-', white_space;
term_op     = white_space, '*' | '/', white_space;
white_space = { ' ' } ;
